### ISSUE TITLE
Updating state without using store.update

### ISSUE THREAD

**Issue by timuster** [lostpebble/pullstate#105]
First of all, great job on the project! It's the only plugin I've found that does what I need without overcomplicating things :)

I accidentally found out that I could manipulate the global state directly (without using the store.update() function as described in the documentation.

Here's a snippet of code that actually works for me:

    const myStore = FormEditStore.useState(s => s.bookingNodes);
 
    function init_working(){
       myStore[id] = 'foo';   // manipulating directly works, and all other components see the updated state/object
    }

Now, if I use the .update() function, as described in the doc, things don't behave in the way I'd like them to (**on initial render**):

    const myStore = FormEditStore.useState(s => s.bookingNodes);
    
    function init_notworking(){
        let temp = myStore;
        temp[id] = 'foo'
        
        
        // other components do not see the right value (on only the initial render; subsequent state changes work as expected)
        FormEditStore.update(s => { s.bookingNodes = temp })
    }

I am certainly not complaining, and for me personally, this is more of a feature than a bug but I'd like to understand if this is expected (I certainly didn't see anything in the docs).

**Comment by timuster** [comment]
This is what the store file looks like btw:

```
import { Store } from "pullstate";

export const FormEditStore = new Store({
  bookingNodes: {}, 
});
```

**Comment by lostpebble** [comment]
Hi @timuster ,

Pullstate expects you to never mutate the state directly on the stores. The only way to update your state is through `.update()` or `.replace()`.

I'm unsure what you're trying to achieve with `init_notworking()` and what exactly is not working in this scenario?

If you really need to get the current state of the store outside of an update, you can make use of `Store.getRawState()` - though again, this is not the best way to do things, and you should confine your updates to `update()` or `replace()` as much as possible.

```ts
function init_working(){
   myStore[id] = 'foo';   // manipulating directly works, and all other components see the updated state/object
}
```

I'm unsure how this is working for you. There is no internal update being run on the pullstate store- so it shouldn't update components which are listening to this state. Because you are mutating the state, when they mount again- they will probably see the new mutated state- so maybe that's what's happening somewhere? Perhaps you've triggered a waterfall effect outside of Pullstate somewhere on this update. But again, this is bad practice and can only lead to hard to find bugs and inconsistent UI I think.

Anyway, let me know what you're trying to achieve here as I'm a little bit unsure how to help you. Generally everything you need to do should be achievable using the functions given to you by pullstate.

**Comment by timuster** [comment]
@lostpebble Thanks for the response! What I need to do is update a key-value object on the first load of my application from multiple components simultaneously.

I have the state initialized as an empty object in my store file `bookingNodes: {}`.

Let's imagine that I have 2 components - in component A, I want to update my global state so that bookingNodes gets set to `{"id_a": "value_a"}` and then in component B, I want to update it so that I finally have `{"id_a": "value_a" , "id_b" : "value_b"}`.

What I found was that using the method depicted in `init_notworking()`, i.e. using the `update()` function, was causing component B to not pick the update that component A had made to the global state, and so I would end up with just `{"id_b": value_b} at the end.

I also found out that if I added an interaction to either of the components (let's say a button), and then had them update the global state on a click, then the other component was able to pick the update - and **so it seems like there is some sort of a race condition on initial render** when using `update()` from multiple components simultaneously. 

Here's an image with the depiction of what I mentioned above. I would really appreciate any ideas - let me know if you'd like me to upload the actual code snippet.


![image](https://user-images.githubusercontent.com/2242052/111254712-01912e80-85ec-11eb-9b90-3e1900f72e28.png)

**Comment by lostpebble** [comment]
Ah, okay. Well what you're trying to achieve is definitely considered an "anti-pattern". Updating state during a render is not the way to do things generally- your stores should inform what your UI looks like, not the other way around. This is the same for regular React as well- you wouldn't run a `setState()` directly after `useState()`- I understand that it feels different because its "global" with pullstate, but it's the same idea- you can think of the state selection in `Store.useState()` as a regular local `useState()` setting the initial state to what you select from the global store.

I'm curious what your use case is here. What's preventing you from adding the state to the store in the events which precede the adding of those components? Or better yet, have those components be mounted in reaction to the current state of `bookingNodes`- not the other way around.

If you truly had no other way, what I would try is running this in each of your components:

```ts
useEffect(() => {
  FormEditStore.update(s => {
    s.bookingNodes[id] = "foo"
  })
}, [])
```

Though, because you are running an update on render, this will trigger an immediate re-render- which is not great. But it will only run once at least, because `useEffect` is set to run once during mount because of the empty deps: `[]`.

**Comment by timuster** [comment]
Well, I'm updating state in the useEffect hook of the 2 components - is that still considered anti-pattern?  

> I'm curious what your use case is here. What's preventing you from adding the state to the store in the events which precede the adding of those components?

I could lift the operation to the parent component, but I am trying to isolate the data processing to the sub-component level, and so component A does some calculation on the data  and adds it to the global state, and then similarly component B does it's thing and updates the global state (in each of their individual useEffect hooks).

I did try the code snippet you provided - it was actually my original approach that was **not working**. What happens, in this case, is that component B (which runs later), does not pick the update made by component A. The diagram I posted in my previous comment illustrates the behavior. 

I'd be happy to provide a code sample if you'd like to dig into this further.

**Comment by lostpebble** [comment]
> I could lift the operation to the parent component, but I am trying to isolate the data processing to the sub-component level, and so component A does some calculation on the data and adds it to the global state, and then similarly component B does its thing and updates the global state (in each of their individual useEffect hooks).

Hmm okay. I'm still not sure why this can't be achieved in a more "best practice" kinda way... I'd need to see the layout of your app to figure it out more. You can still isolate data processing to sub-components without having to run state updates on mounting those sub-components. You just need to have set the state up in the global store before mounting the components, and have the components accept an `id` as a prop which refers to the state they should read and edit.

Another way would be to isolate the sub-components completely from the global store, as purely functional components, and have them create and edit the required state locally- and have the parent component pass down a function like `onSave()` or whatever, which then updates the global store with the edits.

All in all, a rule to try and follow (as I said earlier): Your state should inform what your UI looks like, not the other way around. The only time the UI should inform the global stores is by events triggered in those UI elements- which again makes the next store state inform what the new UI looks like.

But if you can't avoid it- then using the `useEffect()` update method I showed before should work fine.

**Comment by lostpebble** [comment]
@timuster gonna close this as I think we've covered ways to get around your predicament and the best practices that you could look if you want to approach it in a more optimal way (though if its just a few components I don't think its going to have a massive difference).

Let me know if you are still struggling or this isn't really resolved for you.

**Comment by timuster** [comment]
@lostpebble Thanks again! I have it working through the method you recommended. I owe you a beer if you're ever in the US :) Cheers!
