### ISSUE TITLE
"ridiculously simple"

### ISSUE THREAD

**Issue by EmmaB** [lostpebble/pullstate#157]
Hi, would you be happy to remove this phrase from your readme? If it was ridiculously simple, I wouldn't be here, reading the docs. Many thanks.

**Comment by lostpebble** [comment]
I'm not sure. I do think it is ridiculously simple, especially relative to other state libraries in this space (Redux etc.). The docs barely go further than a single browser page's height in order to understand everything you need to know.

I have read your blog post on the subject and I understand where you are coming from. Charged language like this is all to commonplace in tech. I might remove the "ridiculously" part- but I do honestly believe that this library is extremely simple to understand, especially when viewed in the context in which it exists- and in this space I feel that this is an important consideration as well. A lot of the time people just want something to get up and running with, and I think its okay to "market" your library that way if you truly believe it offers that.

**Comment by EmmaB** [comment]
I do appreciate your thoughtful response. I would only say that you think it's simple -- you wrote much of it! -- but I don't. So it depends who you're writing for. If you're the audience -- agreed, it must feel extremely simple. But if it's me, or someone newish to React who is still grappling with the mere idea of state, or who has encountered your code in an app cold, rather than seeking it out with their own problem in mind, then all that does is block me from trying to read the docs and unblock myself, because I'm demoralised, feeling it should be easier.

I think perhaps a nuance is that yes, agree, the code and approach is minimal, but that doesn't make it simple to integrate into what I'm trying to do. I could get on board with "ridiculously minimal"! 

I'll leave it with you to mull: I really appreciate you engaging with me. All the best!

**Comment by atmosbear** [comment]
I want to comment and say that I respectfully disagree. I just began learning React about a week ago, and this is honestly the simplest state manager that I could find (which is why I decided to use it)! I think it's important to have some sort of advertising, including words such as "awesome", etc.

Please don't take the "ridiculously simple" to be an insult if you don't understand it!! It just means you aren't familiar with the core ideas behind this library because you're a beginner with it!

Just as an aside, I recently looked at MobX and Redux and a few others, and I forgot which one, but one of them goes "It's as easy as 1-2-3!" and then it posts a 50 line codebase basically. I was like... bruh, in what universe is this easy?! Maybe to someone who has been doing React for a year or so!

Meanwhile with pullstate, I find myself saying "wait, so... I just call this?" and it works!

Have you tried making something more simple, like a button that updates? I can't believe it works!
