### ISSUE TITLE
State update not triggering

### ISSUE THREAD

**Issue by julianeden** [lostpebble/pullstate#169]
EDITED: I posted this issue after 5+ hours of trying to debug it. I went and had dinner. I came back. I figured it out immediately. I've removed my prior question; so sorry for cluttering your issues board. Again, problem was between keyboard and chair, pullstate is great as always.

**Comment by lostpebble** [comment]
"problem was between keyboard and chair" - hahah, love that.

Glad you got it sorted!

**Comment by Crafter-Y** [comment]
can you share your solution?

**Comment by julianeden** [comment]
For me the problem was nothing to do with pullstate - the issue was that another part of my project was bugged such that the server was placed in a race condition with multiple competing requests.

If pullstate isn't triggering the state update for you, I would go through all the code related to triggering the update - that is to say, the code you *believe* to be working - and independently verify that each successive aspect of the code is definitely doing what you think it's doing.

**Comment by Crafter-Y** [comment]
Thank you for the quick reply. 

My state is updating after some time, so we clearly don't have the same problem. I use the Store.useState() in several places and update my state via Store.update(). The changes don't get reflected immediately. I thought your problem was similar to mine, but it apparently isn't.
