### ISSUE TITLE
High level brainstorming on the future of State Management

### ISSUE THREAD

**Issue by brillout** [lostpebble/pullstate#19]
Why do we tightly couple state management with aesthetics?

React used to prone a separation between "smart" and "dumb" components. How about going one step further and implementing state management *entirely* independently of the view layer?

State management is business logic and is almost always entirely independent to aesthetics, CSS and HTML/DOM.

Why not doing state management entirely independently of React/Vue/Browser/iOS/Android/...?

**Comment by lostpebble** [comment]
Pullstate is already pretty much independent of the view layer. It just includes some nice React bindings in the box. In the future, I'd definitely look into adding other view library bindings as well and maybe separate it all out into separate packages too.

You can use Async Actions and regular state stores without React, but there is plenty of useful code integrated for keeping your React components up to date with the current state, in both regular state and asynchronous state - these "hooks" could easily be integrated with other view layers.

> State management is business logic and is almost always entirely independent to aesthetics, CSS and HTML/DOM.

I agree, the actual business logic of state management should be entirely independent, and with Pullstate it is - the stores themselves do not rely on any view layer code from React, they exist very simply on their own and with `immer` for update management. This was actually my main reason for building Pullstate, to simplify state management and decouple it from being too tightly integrated with the view layer. You can update your state from any JavaScript code, not only from inside components. But the important next step is synchronizing that state with a view layer of your choosing, and this is what Pullstate currently has built-in for React and could be easily extended for others too.

I will just say that keeping that view layer updated consistently and performantly with your application state, especially with async state, is no easy task. Every view layer is different and would require a different approach. And that's why the majority of Pullstate's code is actually the React implementation of that. I use React extensively, and I'd rather do one thing really well than many things half-assed, so that's why React is the main focus for now.

> React used to prone a separation between "smart" and "dumb" components. How about going one step further and implementing state management entirely independently of the view layer?

Pullstate is exactly this already. Its as far removed from the view layer as it can be. But you can't have a view layer completely independent of your app's state (unless your app is somehow stateless), so yea, there are bindings which try and make that connection as simple as possible.

**Comment by bitttttten** [comment]
You might like this talk from Michel Weststrate @brillout 

https://www.youtube.com/watch?v=3J9EJrvqOiM

I don't mind having smart and dumb components, although sometimes the smart component was quite an unnecessary abstraction. You can use pullstate without a view layer, you can set your store to the global scope and change your app around from there. `window.myStore.update(s => { /* trigger an update /* })` for example. If you have connected your component up with `useStoreState`, it will re-render. You can never get away from doing the "plumbing" of getting your state into your component, which is what pullstate helps you and gives you some bonuses on top of that.
