### ISSUE TITLE
Retaining types when using wrappers around pullstate

### ISSUE THREAD

**Issue by davej** [lostpebble/pullstate#2]
Just a usage question since I'm using Typescript for the first time. Feel free to close this and not answer if you're busy. :)

I have only one store in my app so I want to wrap the existing functions in helper functions that provide the store parameter.

So, in JS it would be this:

```jsx
import {
  Store,
  useStoreState,
  InjectStoreState
} from 'pullstate';

export const mainStore = new Store(state);

export const useStore = (substate) => useStoreState(mainStore, substate);
export const update = (updateFn) => mainStore.update(updateFn);
export const InjectStore = ({ on, children }) => (
  <InjectStoreState store={mainStore} on={on}>
    {injectedState => children(injectedState)}
  </InjectStoreState>
);
```

What is the best way to provide types for these functions that rely on the existing type annotations that you have provided in pullstate? I presume I need to be looking into generics but I'm finding it tough to get my head around.

**Comment by lostpebble** [comment]
Hey!

Cool, so basically this should work for you to get some nice types on your `useStore` and `update` functions:

```
import { Store, useStoreState, InjectStoreState, IPropsInjectStoreState } from "pullstate";
import * as React from "react";

interface IMainStoreState {
  primaryColor: string;
  secondaryColor: string;
}

export const mainStore = new Store<IMainStoreState>({
  primaryColor: "red",
  secondaryColor: "green",
});

export const useStore: (<SS>(getSubstate: (state: IMainStoreState) => SS) => SS) = substate => useStoreState(mainStore, substate);
export const update: (updateFn: (state: IMainStoreState) => void) => void = updateFn => mainStore.update(updateFn);

interface IPropsInjectMainStore<SS extends any = any> {
  on?: (state: IMainStoreState) => SS;
  children: (output: SS) => React.ReactElement;
}

export const InjectStore: (props: IPropsInjectMainStore) => React.ReactElement = ({ on, children }) => (
  <InjectStoreState store={mainStore} on={on}>
    {injectedState => children(injectedState)}
  </InjectStoreState>
);
```

Usage:

```

const primary = useStore(s => s.primaryColor);

update(s => {
  s.secondaryColor = "purple";
});

const SomeComponent = () => {
  return (
    <div>
      <InjectStore on={s => s.primaryColor}>{(p: string) => (<div>Primary color is {p}</div>)}</InjectStore>
    </div>
  )
};
```

Are you using Server-rendering by any chance? Because this would get slightly more complicated then - as you'd need to make use of React's context to get your stores.

If you are only doing client-side rendering, then you're all good!

Oh, and the inner type that gets injected into `children` on `<InjectStoreState/>` is pretty impossible to get working as Typescript currently stands (would love to be proven wrong though) - it appears you can't create dynamic return types, which the `on` prop does. The only thing I recommend at the moment is to cast to a certain type in your render - like I did in this example (casted to `string`).

**Comment by davej** [comment]
Thank you for the comprehensive reply, that's awesome.
Out of interest, is there some documentation on what the `SS` does? Is it some type of generic?

**Comment by lostpebble** [comment]
Yep, `SS` is basically just a generic type there. It represets "SubState", hence I named it `SS` - but you could make it whatever you want.

Because the `getSubState()` function over there has the potential to return a different value each time which we can't know in advance, we use a generic type to represent it, and then we can pass that generic type as the return type of the entire function. TypeScript will then figure out the type dynamically, depending on what you return from `getSubState()` each time.
