### ISSUE TITLE
Persist state in React Native app

### ISSUE THREAD

**Issue by supercranky** [lostpebble/pullstate#23]
Hello! 

This project looks amazing! Just what I was looking for.

Do you think it would work without issues in a React Native app? And also, what would be the simplest way to persist changes to the store using AsyncStorage? (it's like LocalStorage but for React Native apps)

**Comment by lostpebble** [comment]
Hi there!

Glad you're enjoying it :)

I have actually used this in a React Native app for fun, and it works fine from what I could see. As it just makes use of the basic react module, and doesn't rely on the DOM at all.

You can see my little test app here (its a Sudoku game):
https://github.com/lostpebble/pullstate-sudoku-react-native

> And also, what would be the simplest way to persist changes to the store using AsyncStorage? (it's like LocalStorage but for React Native apps)

I've actually made a utility to do just that with LocalStorage. You can see it here and adapt it very easily for AsyncStorage. I copied the code into a gist here:

https://gist.github.com/lostpebble/be0ed70f07fa30e45fc47986dfbfa635

I'm definitely considering modularising these kinds of things out into some utility libraries eventually, such as `@pullstate/store-local-storage`,  (perhaps `@pullstate/store-async-storage`) etc. Will have to see when I can get around to it, because it would require a little bit of refactoring of the repo.

Anyway, I hope that answers all your questions :)

**Comment by supercranky** [comment]
Fantastic! Thank you. I will continue experimenting :)

**Comment by changleecc** [comment]
@supercranky - did you manage to figure out how to persist state within React Native?

**Comment by supercranky** [comment]
Yes, it was really easy! I did something like this

`  let getData = async () => {
    try {
      const value = await AsyncStorage.getItem('@userData');
      if (value !== null) {
        let saved = JSON.parse(value);
        UserStore.update((s) => {
          for (let key in saved) {
            s[key] = saved[key];
          }
        });
      }
    } catch (e) {
      console.log('error reading stored value');
    }
  };

  await getData();

  UserStore.subscribe(
    (s) => s,
    (userStore) => {
      AsyncStorage.setItem('@userData', JSON.stringify(userStore));
    },
  );`

**Comment by lostpebble** [comment]
@supercranky , you could also potentially make use of:

```ts
UserStore.replace(saved);
```

Instead of iterating through the entire store. Though this isn't documented on the main documentation site yet, only in the Store API doc: https://lostpebble.github.io/pullstate-typedoc/classes/store.html

**Comment by supercranky** [comment]
@lostpebble Even better! We're actually using pullstate in a live production app now and it has worked out great

**Comment by lostpebble** [comment]
Great! Glad to hear :)

**Comment by changleecc** [comment]
Amazing stuff. Thanks a ton @supercranky and @lostpebble ! Coming from Redux and Sagas extensively I am really enjoying the hooks-like freedom pullstate is offering.
