### ISSUE TITLE
What is action? Docs problem

### ISSUE THREAD

**Issue by OnkelTem** [lostpebble/pullstate#30]
Hi!

I'm reading docs now and I don't feel confident because the documentaion lacks important details and  vague to some extent.

The first chapters are ok, except for Server Rendering which I just skipped - too many details I don't really need for now. There are also many minor issues like missed imports however.

Then comes Async Actions chapter. Without any explanations of what Sync Actions are it starts discussing Async Actions.

## Url: https://lostpebble.github.io/pullstate/docs/async-actions-creating
Section: The action itself
`useStoreState` is not used, should be removed from the imports.

Section: Update our state stores with async actions
Here the imports section is just missed.

## Url: https://lostpebble.github.io/pullstate/docs/async-action-use
Section: Watch an Async Action (React hook)
```
const [started, finished, result, updating] = GetUserAction.useWatch({ userId }, options);
```
What is `GetUserAction`? Is it a part of Pullstate API which you forgot to mention? The imports are missed too so it becomes unclear.

Section: (React Suspense) Read an Async Action
```
const posts = getPostsAction.read({ userId: "lostpebble" });
```
Now I really doubt `GetUserAction` was a Pullstate API thing. So probably both `GetUserAction` and `getPostsAction` are user-defined ones. Then **how and where they are defined**? Why they are object, how do they acquire those hooks?

```
  <Suspense fallback={<div>Loading Posts....</div>}>
    <RenderPosts/>
  </Suspense>
```
What is `Suspense`. What is fallback and why are they here?

## Url: https://lostpebble.github.io/pullstate/docs/async-post-action-hook
section: DO NOT DO THIS!
```
const searchPicturesForTag = PullstateCore....
```
What is PullstateCore and why is it called like that? In the previous examples it was just Pullstate I believe.

And I haven't finished reading yet...

P.S. Please don't say that Pull Requests are welcome, because first - I know they are, and second - I'm not qualified enough to produce some nice and shiny PRs, I'm just a user trying to read some docs.

**Comment by lostpebble** [comment]
Hi there,

Thanks for letting me know the docs are not up to scratch. I have been looking into your concerns and am trying to rectify them.

Some notes for now:

> Section: The action itself
useStoreState is not used, should be removed from the imports.
> Section: Update our state stores with async actions
Here the imports section is just missed.

Fixed.

> What is GetUserAction? Is it a part of Pullstate API which you forgot to mention? The imports are missed too so it becomes unclear.

I see how that's confusing. I've now added a note, and I'm making use of the action which was created in the first "create async action" section of the docs.

> What is Suspense. What is fallback and why are they here?

Okay, it was my mistake to not mention anything. But right now, this feature is mostly for advanced React users who want to make use of the future React feature of Suspense. You can read more about it here: https://reactjs.org/docs/concurrent-mode-suspense.html

I've also added a note about it now.

> What is PullstateCore and why is it called like that? In the previous examples it was just Pullstate I believe.

As explained in the creation section for Async Actions, `PullstateCore` is for server-rendering and its a place that gathers all your stores together so that they can be referenced during each render of your app on the server. If you are not using server-rendering, then don't worry about it and just import and use your stores directly. I've added some extra info there to try and help.

> P.S. Please don't say that Pull Requests are welcome, because first - I know they are, and second - I'm not qualified enough to produce some nice and shiny PRs, I'm just a user trying to read some docs.

This was a little unnecessary.

Anyway, thanks again. If you have any other comments please feel free to let me know and I'll try and clear things up for you and future others.

**Comment by OnkelTem** [comment]
Thanks! I'm still reading the docs :)
