### ISSUE TITLE
User authentication example

### ISSUE THREAD

**Issue by OnkelTem** [lostpebble/pullstate#31]
Could you please provide some example of an app with user authentication?

In our apps we use **redux** for state management, and **sagas** - for async data exchange with the remote API. 

Specifically, we track the following activity (actions):

* USER_LOGIN_REQUEST
* USER_LOGIN_PENDING
* USER_LOGIN_SUCCESS
* USER_LOGIN_FAILURE

Login user saga looks like this:

```js
function* loginUserSaga({ credentials }) {
  try {
    yield put({
      type: USER_LOGIN_PENDING
    });
    const {user, timeout} = yield race({
      user: call(api.user.login, credentials),
      timeout: delay(LOGIN_TIMEOUT_SEC * 1000),
    });
    if (timeout) {
      throw new Error("Login timeout, check your network connection.");
    }
    else {
      localStorage.user = JSON.stringify(user);
      yield put({
        type: USER_LOGIN_SUCCESS,
        user
      });
    }
  }
  catch (e) {
    // noinspection JSCheckFunctionSignatures
    yield call(throwError, USER_LOGIN_FAILURE, 'Error logging in', e);
  }
}
```

In the real app we also track more states but the above ones are the most interesting.

I wonder how to implenent similar functionality using pullstate?

**Comment by lostpebble** [comment]
This is actually outside of the scope of this project, because everyone does user authentication differently - and Pullstate's domain is simply focused on giving you the tools to do easy state management - how you actually use this state management (including user auth) is totally up to you and outside of the library.

But, I'll show you a simple example of how one might do it (client-side only):

```typescript jsx
const UserStore = new Store({
  state: USER_NOT_LOGGED_IN,
  user: null
});

// N.B. this kind of update only works on client-side only apps,
// since we're using the "globally" defined UserStore directly
// instead of the one from <PullstateProvider/> or our Pullstate instance
const updateUserState = newState => {
  UserStore.update(s => {
    s.state = newState;
  });
};
```

Then using your code (changed to async/await because I've never used generators / yield):

```typescript
async function loginUserSaga({ credentials }) {
  try {
    updateUserState(USER_LOGIN_PENDING);

    const { user, timeout } = await race({
      user: call(api.user.login, credentials),
      timeout: delay(LOGIN_TIMEOUT_SEC * 1000)
    });

    if (timeout) {
      updateUserState(USER_LOGIN_FAILURE);
      throw new Error("Login timeout, check your network connection.");
    } else {
      localStorage.user = JSON.stringify(user);
      UserStore.update(s => {
        s.state = USER_LOGIN_SUCCESS;
        s.user = user;
      });
    }
  } catch (e) {
    updateUserState(USER_LOGIN_FAILURE);
    e.message += " (Error loggin in)";
    throw e;
  }
}
```

And now, since you are tracking your user and the current login state in the `UserStore`, you simply use that in your components:

```typescript jsx
const LoginPage = () => {
  const [credentials, setCredentials] = useState({ name: "", password: "" });

  return (
    <div>
      {/* Put your inputs etc. here for the credentials */}
      <button onClick={() => loginUserSaga({ credentials })}>Log in</button>
    </div>
  );
};

const App = () => {
  const { state, user } = UserStore.useState();

  if (state.USER_NOT_LOGGED_IN) {
    return <LoginPage />;
  }

  if (state.USER_LOGIN_PENDING) {
    return <LoadingLogin />;
  }

  // ... etc.
};
```

That's very simplified example, and you would of course set up your interface very differently - but I think you can get the general idea from that.

I hope this shows to you a bit that you can do pretty much whatever you like with Pullstate depending on your state needs - its much like redux etc. There is no "one way" to do anything, its simply a toolset to help you achieve whatever you want in an easier and more straightforward manner.

**Comment by OnkelTem** [comment]
Thank you very much, at least now I'm starting to get the whole picture of where or how it can be used.

This is not the whole story though. 
First, I'm not sure if `loginUserSaga` is still a valid saga function as it really expects a generator there. 
Second, we don't trigger sagas directly, instead we're building a complex pile of things:

- there is an action function which emits redux action
- which is received by a sagas generator function
- which when is being executed emits actions again
- which are rececied by reducers
- which update state

Phew! See now why I'm looking for a better solution Paul?

Let's do the following. I'm gonna cook a simple sandbox app with basic auth thing implemented using the above technique. And then we'll see how to do the same using Pullstate. What do you think?

**Comment by lostpebble** [comment]
Looking closer you should not use `saga` at all with pullstate - that's clearly a **redux** methodology. Pullstate is not redux, its a simplified replacement for redux - so "saga" doesn't apply.

With Pullstate you simply just update your store when the time is necessary using `YourStore.update()` method, and your components will react accordingly depending how you're listening to that state.

I feel like you might be over complicating this a bit. User auth shouldn't be anything more than calling an asynchronous API method and setting the result in your stores, as well as setting the intermittent states in your stores to keep the interface updated. The key method in this example is:

```ts
await race({
  user: call(api.user.login, credentials),
  timeout: delay(LOGIN_TIMEOUT_SEC * 1000)
});
```

I should have just renamed your function there completely from `async function loginUserSaga({ credentials })` to `async function loginUser({ credentials })` - its not a "saga" its just a simple asynchronous login flow which we are keeping track of easily in our `UserStore` as needed.

> Let's do the following. I'm gonna cook a simple sandbox app with basic auth thing implemented using the above technique. And then we'll see how to do the same using Pullstate. What do you think?

If you like, that's fine. I can't make any solid commitments though, as this is getting a bit outside of the scope of Pullstate and I unfortunately have some heavy commitments to other projects at the moment.

**Comment by OnkelTem** [comment]
I agree that I'm probably overcomplicating things. But this is not actually me - this is our redux-saga way unfortunately. I feel like Pullstate can make many things more simple.

Maybe it was the main idea behind Pullstate's to emulate redux-saga, but yet - the task of authenticating user is frequent and it's also a good example of async workflow in a react app.

Unfortunately there are no videos on YouTube about Pullstate and even Google fails on providing Pullstate articles as well. I think people just get lost when they have only official docs at their disposal.

**Comment by lostpebble** [comment]
Yes, but as I mentioned - Pullstate simply gives you the tools to make state management easier.

Pullstate is not a massive all-encompassing solution to all your dev problems - user auth is one of many application development problems - for everything outside state management, you will need to use your own logic for plugging that into Pullstate- which has been made very easy because its really just a simple `Store.update()` in most cases.

This flexibility is what allows it to be so simple and allows people to build all kinds of applications on top of it very quickly- but don't expect it to tell you exactly how to work with it on your specific development problem.

Pullstate aims to move away from the "redux" way of thinking, which is very verbose and makes you feel stuck in a certain rigid way of doing things. If you look at the example I showed you here, you can see that you have complete freedom to use Pullstate in which ever way you like, its really just a simple object which you update and which you can listen to changes on in your React components.

I'm not sure what else I could show you about authentication and Pullstate - the example I made for you earlier really does cover a simple way that you could use it, and you can expand easily on that.

**Comment by OnkelTem** [comment]
We can continue discussing semi-philosophical matters. Or we can make code.
I vote for the latter.

**Comment by lostpebble** [comment]
No need to be rude.

I'm not here to hold your hand. Pullstate is as simple as libraries come, if you can't integrate that with your workflow, that's not my problem. It was never Pullstate's problem either. Its been specifically designed to be simple and bare minimum - the rest is up to you and the libraries you choose to integrate with it.

> I'm not sure what else I could show you about authentication and Pullstate - the example I made for you earlier really does cover a simple way that you could use it, and you can expand easily on that.

I've already taken plenty of time out my extremely busy day to try and guide you here. But I think its clear that I'm done here now.

**Comment by OnkelTem** [comment]
It's all about efficiency.
We've already spent more time than we would need for preparing real example which could in their turn help people to start using this library, all right?
But instead we've been having some vague conversation without any specific purpose.

And no - I don't need you to make programming for me. I've been trying to help you make your product better. But apparently you couldn't grasp this simple idea.

**Comment by lostpebble** [comment]
> I've been trying to help you to make your product better. But apparently you couldn't grasp this simple idea.

The product is fine as it is. It does exactly what it says on the box, nothing more and nothing less. This is clearly a user problem.

I could have just told you this issue is outside the scope of this project and you'd have to do what programmers do: **understand the tools you are given and build your own solutions** - BUT I wanted to be nice and instead I did my best to help explain a way you could do it and created an example for you, but you still can't seem to wrap your head around it and choose to resort to rudeness and being a smart-ass.

You are seriously so entitled, and I won't be helping you any further. Please don't leave any more comments on this project.
