### ISSUE TITLE
Single store vs. multiple stores

### ISSUE THREAD

**Issue by andraaspar** [lostpebble/pullstate#33]
Hi and thanks for this solution! You are my hero! I wish I could star this even more!

After reading the docs I wasn't sure how to structure my stores: single deeply nested store vs. multiple shallow stores. Are there any drawbacks to having multiple stores? (I guess you can't update them in one step, but is that an issue?)

**Comment by lostpebble** [comment]
Hi there!

Thanks for the kind words :) Glad its helping you out.

So, there aren't massive advantages to using more than one store - but I do prefer it for my own projects because its helps to keep things "modular".

That said, off the top of my head, the biggest advantage might be that when you make an update to a store, only its listeners need to react to that update. So using multiple stores means that less listeners are being checked on each update. Whereas if you had your state in one massive store, any update to the store would cause all the update listeners to check if their value has changed - which could potentially be a performance hit if you have some complex sub-state selections or your App is quite large.

So I would personally recommend trying to think modularly about your stores. For instance, I have ones called `UserStore`, `UIStore`, and then multiple other stores depending on different data types and their requirements in my app - `GISStore`, for instance, which encapsulates and takes care of a bunch of Geo-specific data stuff that I need.

> I guess you can't update them in one step, but is that an issue?

Its cool that you actually bring this up :) Because just this past week I've been working on a way to "batch" updates in your stores- multiple updates in a single store, or even multiple updates across all your stores.

I'll release the new version soon, just been "dog-fooding" it in my app a bit to make sure I like the API. At the moment it looks like this:

(You need to make use of your `PullstateCore` object which you create using `createPullstateCore()`, this allows all our stores to be gathered together so we can act across them)

Using one of my apps as an example:

```ts
const PullstateCore = createPullstateCore({
  UIStore,
  UserStore,
  BackendConfigStore,
  PostSearchStore,
  GISStore,
  AdvertisingStore,
  PlaceAndHostStore,
  TagTemplateStore,
  ListedNodeStore,
  SecondaryItemCacheStore,
});

const setupActions = PullstateCore.actionSetup();

export const act = setupActions.act;
export const action = setupActions.action;
```

And then you can create and use (client-side only if you use `act` directly) actions like so:

```tsx
import { act, action } from "./PullstateCore";

const multiStoreAction = (isDarkMode: boolean) => action(update => {
  update.UIStore(s => {
    s.theme.dark = isDarkMode;
  });

  update.GISStore(s => {
    s.customTileLayerUrl = isDarkMode ? "https://example.com/dark" : "https://example.com/light";
  });
});

// ... somewhere in your components on a button press, perhaps
<button onClick={() => act(multiStoreAction(true))}>Set Dark Mode</button>
```

But yea, I'm not entirely sure of the API yet. I'm going to play around a bit more with it over the next few days and see.

**Comment by andraaspar** [comment]
That's what I was going to do, so thanks for making it official. ;) Very neat.

That new API will be very useful. If I may give some initial feedback (I know it is not ready, and you probably haven't told me everything): act and action seems like too much detail. Could they be combined somehow? I love the simplicity of the update method.

Anyway, thanks for pullstate and keep up the good work!

**Comment by lostpebble** [comment]
Appreciate the feedback! And I totally agree with you, the main focus for me is that pullstate is as simple as possible.

In fact, you don't even need to use `action` - its simply a function that makes it easier for you to create actions if you are using TypeScript (it sets up the types nicely for you from `PullstateCore`). It actually simply returns the very same function you passed into it. You could just do this:

(also made even simpler by destructuring `update` as it was above, with `{ UIStore, GIStore }`)

```tsx
// ... somewhere in your components on a button press, perhaps
<button onClick={() => act(({ UIStore, GIStore }) => {
  UIStore(s => {
    s.theme.dark = isDarkMode;
  });

  GISStore(s => {
    s.customTileLayerUrl = isDarkMode ? "https://example.com/dark" : "https://example.com/light";
  });
})}>Set Dark Mode</button>
```

The big problem with making this any easier comes from needing to support server-side rendering. We need to be able to initiate the actions somehow from within our components using the store's passed down for this single server request, hence we always need to make use of a function such as `UIStore.update()`, or `act()` in this example, to instigate those state changes.

Anyway, thanks for the feedback. Definitely want to make this as simple as possible, and perhaps there's still another API that makes it even more so!

**Comment by andraaspar** [comment]
Yep, that looks great! I appreciate the effort you put into it. It is much more natural to use than Redux. I cannot comment on SSR – I have no experience there – but in plain front-end situations it is unbeatable. Finally, React is looking better than Mithril – all thanks to you.
