### ISSUE TITLE
Latest version 1.11.0 doesn't work on IE11

### ISSUE THREAD

**Issue by freewind** [lostpebble/pullstate#34]
Reports error: 

```
SCRIPT5009: 'Proxy' is undefined
```

But old version (e.g. 1.7.2) has no such problem

**Comment by lostpebble** [comment]
Hi @freewind ,

Oh, it must be because I added a `Proxy` in some cases to provide better error messages to users.

I thought it would be fine, since `immer` uses Proxies extensively to achieve what it does - and this library is based off of that. But it seems that they have a workaround for older JavaScript environments.

I will look into rectifying this soon.

For the time being, I think you should be able to use a Polyfill for `Proxy` - using something like 
https://github.com/GoogleChrome/proxy-polyfill
OR
https://www.npmjs.com/package/es6-proxy-polyfill

**Comment by lostpebble** [comment]
In fact, I think this is something that might be outside of `pullstate` itself. If you need to support older browsers, using a Polyfill for modern JavaScript is the recommended way nowadays.

I would like this library to be "evergreen" and able to use the latest technologies without stressing about ancient browsers that should have been phased out ages ago. I do feel your pain if you still need to use them 😥  - I'm sure it sucks, but luckily there are plenty of Polyfills around for certain features.

I'll put a note in the docs / readme about it.

**Comment by freewind** [comment]
@lostpebble Thanks for your suggestion. I tried with "proxy-polyfill", but it still gives me the error:

![image](https://user-images.githubusercontent.com/333781/77419552-96ab7e00-6e03-11ea-969c-533ec9e4831e.png)

Seems like some methods not supported by the polyfill

**Comment by freewind** [comment]
And with es6-proxy-polyfill, it has a different error:

![image](https://user-images.githubusercontent.com/333781/77419802-f43fca80-6e03-11ea-82f5-db869beb3ba0.png)

**Comment by freewind** [comment]
I made a repo: https://github.com/freewind-demos/typescript-react-state-management--pullstate--demo

You can try it to see the errors if you want, I'm not sure if I miss anything. I write the main problem and instructions in English so you might understand it. (You can safely ignore the Chinese part)

Thanks for the great library

**Comment by lostpebble** [comment]
Hi @freewind 

I've just put in a `try {} catch {}` around the creation of the Proxy, so that for older environments it will just ignore it completely. You just won't get as clear an error message if you misuse some parts of Async Actions, but you shouldn't run into those issues if you are using it correctly in the first place ;)

Hope that helps. Try out `1.11.2`

**Comment by freewind** [comment]
Thanks so much for the quick response and new release!
