### ISSUE TITLE
Question about  "target": "esnext" in tsconfig.json

### ISSUE THREAD

**Issue by freewind** [lostpebble/pullstate#35]
I see in the `tsconfig.json`, we have:

```
"compilerOptions": {
    // ...
    "target": "esnext",
}
```

Just wondering why use `esnext` as target instead of `es5/es6`, as the later one can generate safer syntax for some old browsers like IE?

I have this question because I found my app using pullstate can't run on IE11 directly (sadly we have to support it), because there are some syntax is not supported on IE 11, (e.g. `const [a,b] = ...`), so we have to configure our webpack and babel to convert `node_modules/pullstate` files

**Comment by lostpebble** [comment]
Ah, right. Well usually `pullstate` is bundled with your client code, so for the most part it shouldn't matter. But yea, if you need to run it directly in the browser somehow then it might cause issues.

The reason I use the latest JavaScript formats is so that bundling tools can make smarter decisions about how to use Pullstate, with tree-shaking etc. And the code is also a bit smaller when using the latest syntax.

Are you trying to use `pullstate` directly without bundling at all? In like a `<script>` tag on an HTML page? I could see that causing issues in older browsers, yea.

---

As mentioned in the other issue, I know it sucks having to work on those older browsers... I'm not really sure how to find the balance between trying to be modern and forward moving and having to still consider those dinosaurs.

Does IE11 even work with ES6 ? I thought it was lagging behind quite a bit more.

I'm willing to try and find a way that works for people who still have to deal with older JavaScript.. maybe a separate `dist.es6.js` file or something, that might allow you to at least directly import it in `<script>` tags in HTML. Using it with `npm` modules would still be the same though, which should be bundled anyway.

**Comment by freewind** [comment]
Sorry I didn't express it clearly, that I didn't use it with `<script>`.

My projects are normally typescript, and I use webpack to bundle the files.

In my `tsconfig.json`, I set the compilation target as `es5`(it's safer to IE), and use `ts-loader` in webpack to compile my typescript files, and then use webpack to bundle all the code together (also with some polyfill like corejs for IE). I don't need to have special handling for packages in node_modules, it was working well.

But now with pullstate, I found the bundled file contains some code with syntax that IE 11 doesn't support. In order to fix it, I need to add some babel configuration to compile js files in 'node_modules' to convert pullstate to safer syntax, which makes the compilation stage slower.

But this is just my opinion, it's OK to keep it since I have at least some workaround. Just post this question to make it clear. Thanks

**Comment by lostpebble** [comment]
Ah I see, then perhaps I am mistaken in thinking that the bundling would transpile to your target (`ES5`) automatically. I thought that's what Webpack does when it spits out the final bundle... but yea I get confused with all this JavaScript module business sometimes - its all over the place.

If there are more people struggling with this, I'll be happy to consider making it safer all round. Perhaps I should change the compile target because `esnext` is not likely to work in most browsers... I'll think about it some more and see what others are doing.

Thank you for the question and making it more clear! I'm glad you at least have a workaround for now

**Comment by freewind** [comment]
Glad we make it clear.

PS: `esnext` now is `es2020`, and you're right most of browsers don't fully support its new syntax
