### ISSUE TITLE
[Question] How to implement "click on a button then run an async action" in an elegant way?

### ISSUE THREAD

**Issue by freewind** [lostpebble/pullstate#39]
I see the examples of async actions are about "running async actions when rendering a component, e.g. https://lostpebble.github.io/pullstate/docs/async-actions-creating

Now I have a different case: In a component, there is a button, when I click on it, it will run some async actions, and rendering different content base on the result of the async action.

I couldn't find an elegant way to implement it, hope to have your help, thanks!

This is a small demo: https://github.com/freewind-demos/typescript-react-pullstate-async-actions-demo

The `RemoteHello1` there is what I want to do (in traditional way), and the `RemoteHello2` is what I want to use pullstate's async actions but failed.

**Comment by lostpebble** [comment]
Hi again :)

Yes, I feel you. This is something I would like to make more elegant: The watching of an async action which you also want to instigate through a button.

Right now, its still very simple - all you have to do is watch the arguments that you will eventually initiate, and then you run the action with those same arguments, and you will get the current state of the action from your watched async action hook.

There is a new way I've been working on for actions which I think simplifies it all a bit, so I'll show you that method- but this is also quite easy to do using the current way of `useWatch()` instead of `useBeckon()`.

Basically, your `RemoteHello2.tsx` file could have some code like this in it (in the component):

```
const remoteFetch = asyncFetch.use('RemoteHello2', { initiate: false });

  if (remoteFetch.isLoading) {
    return <div>Loading...</div>;
  }

  return <div>
    <button onClick={() => asyncFetch.run("RemoteHello2")}>Fetch remote message</button>
    {remoteFetch.isFinished && remoteFetch.error && (<div className='error'>Error: {remoteFetch.message}</div>)}
    {remoteFetch.renderPayload(payload => <div className='success'>Hello, {payload}</div>)}
  </div>
```

`action.use()` is the newer syntax. If you don't want to initiate the action (only want to watch the execution state once it is called somewhere else) you need to pass `initiate: false` as an option.

It returns an object, as opposed to an array like the current methods. I find this to be a little more readable now, as we can simply check the states on that single object variable instead of destructing an array.

So yea, I sent through a pull request to your repo as well that makes these changes so you can see them live too.

Hope that helps :)

In the future I might look into doing something like this, but there is also a `run()` function in that `remoteFetch` object returned from the `action.use()` method - this allows you to just directly initiate the action somewhere in your component when you like, without having to pass in the arguments again.

**Comment by freewind** [comment]
Thanks for detailed reply! I just tried your code and it's working.

I also tried another library [react-async-hook](https://github.com/slorber/react-async-hook#usecase-injecting-async-feedback-into-buttons), which also provided such a use case, with a `useAsyncCallback` function. It's quite similar to your solution, which has a `execute` to trigger the execution manually.

**Comment by lostpebble** [comment]
Ahh, I see. Yes that's exactly how I envisioned it.

It really should be easy to add, as its just wrapping around `.run(args)`. I'll add it now and see.

Thanks for the link :)

**Comment by lostpebble** [comment]
@freewind , I just updated the project with the new changes I added.

It was actually very simple to add, don't know what I hadn't done it yet. Also made creating simple async actions easier, by just passing in a promise directly.

**Comment by freewind** [comment]
Thanks, the code is really nice and clean, thanks!
