### ISSUE TITLE
No issue - just like to say thank you

### ISSUE THREAD

**Issue by jamuhl** [lostpebble/pullstate#4]
Doing some OSS too: https://github.com/i18next/react-i18next (and https://github.com/i18next/i18next) i personally would like to get more positive Feedback from time to time - so i thought - i say thank you.

I currently work on creating our next product complementing our https://locize.com (https://localistars.com) and started searching an option for state management and side effects handling.

- redux & redux saga we used in the past - it's great but somehow it feels to heavy
- unstated - idk but guess that is a dead horse (unmaintained, unclear direction, guess waiting for fetcher API)
- unistore - no hooks, to much work - action function for every little manipulation
- outstated - looks promising but like you i prefer having the store not in react but separated
- constate - same as outstated but needs even a Provider for every store

So for me there is currently no real state management option covering my own taste - only yours.

You nailed it for me - simple store with simple update statements where needed. And AsyncActions for the heavy lifting (guess fetcher API will be similar).

Not sure about what will happen when the fetcher API lands https://xebia.com/blog/the-future-of-react-is-not-another-state-manager/ best case might be an update on the AsyncActions here.

Do you plan to promote this module more? Or will it be on risk to get unmaintained (which would be ok too - not too much code, well written, so we might maintain our own simplified fork - no need for SSR).

SO  --- THANK YOU!!!

**Comment by lostpebble** [comment]
That is so awesome! Thank you so much for this. Really put a smile on my face and made my day :)

I definitely do plan to work and use this module in my own production code. I run a small startup in South Africa and the app is quite mature already- so this project will definitely be getting plenty of use and growth as I put it through as many state challenges as possible in the upcoming months (working on rebuilding the entire webapp, and easier state management is a big part of the next iteration).

The list of reasons you gave resonates so much with me and the reasons for why I created this library in the first place. I really couldn't find anything that suited my needs for simplicity. I would love to get this out there more, so we get more eyes, potentially more maintainers, and more edge-cases or issues found - I just haven't been very good at promotion. I made a post on Reddit and that was it haha. Seemed to get it up to 26 stars, and that's where its sat for a while now.

Will definitely be keeping an eye on React's next version of async fetching. I think the way its done in Pullstate now is really nice for my use-case - and its very extensible for most needs because the value returned from an AsyncAction has plenty of state information about the execution of it - but the only downside is SSR at the moment requires rendering the React tree multiple times in order to reconcile all async state in the tree before the first render. This is apparently something the React team are focusing on for their next version of async fetching.

Btw, the next big iteration for my webapp involves i18n, as we plan to expand outside of South Africa - and just to cover the local languages in SA too (there are 11 official languages 😅 ) - so I'm definitely going to be looking closer at your project too, it looks great from a quick read through just now!

**Comment by jamuhl** [comment]
Just started integration - looks all clean and good.

And yes - promotion is like documentation - the part i had my hard times with i18next too...

Closing this for now - and thanks again for saving me the time for inventing this on my own....
