### ISSUE TITLE
Any approach to computed getters?

### ISSUE THREAD

**Issue by seivan** [lostpebble/pullstate#43]
Is there a way to define a computed getter that doesn't recalculate unless any of its dependent fields mutated? 

```ts
class Theme {
  [immerable] = true;
  theme = {
    isDark: true
  };
  timesThemeChanged = 0;
  get setOppositeThemeMode() {
      console.log("should only be called once, until theme.isDark changes") 
      !this.theme.isDark;
  }
  setOppositeThemeMode() {
    this.timesThemeChanged += 1;
    this.theme.isDark = !this.theme.isDark;
  }
}
```

[Sandbox](https://codesandbox.io/s/pullstate-lacks-computed-clsy7?file=/src/index.tsx) 
When refreshing the app by mutating setter, it seems to only call the getter once and reuse its value in both components, which is good.
But when editing  by calling `setOppositeThemeMode()` it will trigger  `setOppositeThemeMode` twice. 

Could be related to batch updates, but not 100%.

**Comment by lostpebble** [comment]
This is very strange way of making use of Pullstate. I've never tried what you are doing here with Classes... I'm not entirely sure it will all be completely compatible in the long run, because its built around the fact that your state is stored as an object on the store which is then passed to immer for mutation.

I mean, it looks like it should work - essentially the Class is just an object which you've "immerified" with `[immerable] = true` I assume. I just wouldn't exactly recommend it until I've done more research on it.

---

For the question you're asking though, Pullstate will always compare the previously watched state to the currently watched state to check if React should update its views - this will do a property get for `oppositeThemeMode` when it does the comparison. So there is no way to set this directly on the store's internal object, like you've done here.

There is a different way to do this though, using Reactions (https://lostpebble.github.io/pullstate/docs/reactions). You might define something like this:

```tsx
UIStore.createReaction(
  s => s.theme.isDark,
  (isDark, s) => {
    s.oppositeThemeMode = !isDark;
  }
);
```

This would only run this Reaction, and set the new state in your Store, if `theme.isDark` changes.

I will investigate the Class way of using Pullstate further. And perhaps see if there are better ways to automatically infer Reactions depending on which parts of the store you derive other "calculated" values from.

Thanks for the issue! As this should be solved the Pullstate way with Reactions, I'll close this for now. Definitely some room for automated improvement in the future though.
