### ISSUE TITLE
Redux Devtools integeration

### ISSUE THREAD

**Issue by kickbox** [lostpebble/pullstate#47]
I really like your library. You are doing a really good job! Thank you, Do you plan to support Redux Devtools. I know a similar state management package does [this](https://hookstate.js.org/docs/devtools). 

Redux Devtools would be great because debugging is difficult in my Google App Script project and a devtool like Redux can be easily setup for testing in react production environment .

**Comment by lostpebble** [comment]
Hi @kickbox ,

Devtools is definitely something I've been wanting to add- and it actually isn't too technical, thanks to `immer` and the ability to track each and every patch change to your stores. Could actually enable some really cool time-travel-able tooling.

I suppose integrating with something like Redux Devtools first might be good. If its easy enough to plug into. Though a native solution would be cool at some point too.

What kind of features are you looking for in something like this?

**Comment by kickbox** [comment]
Wow that's encouraging to know. I would like just the basic stuff.
Viisibility into live states values and debug state updates.

**Comment by lukasmoellerch** [comment]
Hi @lostpebble I was thinking about using your library - which looks really good - in a React project, was looking for devtool support and stumbled upon this issue. I think that integrating with redux devtools would actually be fairly easy to achieve using the API that already exists. To connect to Redux DevTools  the library would have to `connect` and subscribe both to the store state using your API and to DevTools events using their `subscribe` API. A good start would probably be to handle the `DISPATCH` event which would already allow time-travel and jumping to a specific point in time. I created a small PoC here: https://codesandbox.io/s/pullstate-client-only-example-77iom

Somehow it isn't enough to use `SomeStore.replace` to set the store state in nontrivial examples. The method also isn't documented so I used `SomeStore.update` and recursively synchronized the objects (not clean at all :D). Works ok in that example and the sudoku example works as well.

**Comment by lostpebble** [comment]
Hi @lukasmoellerch 

Looks great! And much easier to plug into than I thought before.

I do wonder why `Store.replace` didn't work, as it makes use of the same update process behind the scenes (just without the actual immer update function). Will investigate that further, as it would simplify this even more. But well done on making it work in any case!

Going to check things out a bit today and try put in the integration you worked out here. I would preferably like to catch all stores, as right now you are just targeting `UIStore`, and it doesn't seem like redux devtools allow for tracking more than a single state object? Would be nice if they had the ability to tab between them.

Also, I'm not sure what people would want? Perhaps tracking a single store is desired. Though... potentially the interface could look like this, giving people the choice:

```ts
import { registerInDevtools } from "pullstate"

registerInDevtools({
  UIStore,
  PostStore,
  UserStore
})
```

Which will just create and track all those stores' states, the "tree" will just start with the branches of the store names.

**Comment by lukasmoellerch** [comment]
I just did a quick test again with `replace` because I was using an old version (1.4), but it still didn't work. I saw that `.update` calls `_patchListeners` whereas `replace` doesn't - maybe that's was the issue? I was using your sudoku example which uses a `listenToPatches`. My `subscribe` triggers, but the UI doesn't update. If I call `_updateState` directly and supply a `updateKeyedPaths: Object.keys(...)` argument shallow properties work and deeply nested properties probably do as well, but I don't see an easy of constructing all of them. Can this maybe be solved by passing something like an update-all flag to `_updateState` so that all `optimizedListeners` are updated? (Your `App.tsx` uses `useStoreStateOpt`)

Regarding multiple stores - it seems to be possible by having multiple instances: https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.0.0 I would prefer that instead of having them in a single state tree. That would mean that that `registerInDevtools` could also very well be a method of a `State`.

**Comment by lostpebble** [comment]
Ahh, okay. Yea, then that might be the main issue with the Soduku example - as `replace` will not function properly.

The soduku example needs to be updated. I used an experimental way of using Pullstate, which makes use of watching the patch changes (the paths of the state store that changed) instead of using a selection function. It is more performant in very large state trees, but its also quite convoluted and had some issues. So for now, Pullstate is sticking with the documented methods of state updates / using. The replace function is just a complete replace of the entire store's state - so the patch listeners don't come into play at all - though it wouldn't be too hard to implement. But yea, there are still issues with the implementation as a whole there.

> (Your `App.tsx` uses `useStoreStateOpt` - which would explain why the UI didn't update)

Exactly. That's the "optimized" state listener which makes use of patches.

> Regarding multiple stores - it seems to be possible by having multiple instances: https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.0.0 I would prefer that instead of having them in a single state tree. That would mean that that registerInDevtools could also very well be a method of a State.

That's great news, and simplifies things quite a lot now. We can definitely have a method on a store now, like `Store.registerInDevtools()` to take care of selecting which state you want to listen to, with the ability to listen to multiple stores. Nice.

---

All that said, even with the basic example of pullstate, I was getting an error when using `replace`... so still investigating and fixing that now, so we can use that method for the devtools side of things.

**Comment by lukasmoellerch** [comment]
I would've expected a `useStoreStateOpt` listener to update also if a parent changed - is that not yet implemented? (i.e. if something listens to `["a", "b", "c"]` I would expect that it is called when `"a"` is updated)

I am not getting any error when using `update`, but had a second thought about `registerInDevtools` being a method: That would reduce tree-shakability of the package especially if developers want to exclude the `registerInDevtools` calls in production. It also means that we wouldn't have any solid method of getting the store name, because the constructor name will be minified by e.g. terser. That would leave us with two options: Adding a parameter to `Store.registerInDevtools` or sticking with `registerInDevtools({ UIStore })` which you preferred at first. I also noticed that I was using you `subscribe` API in a a wrong way... We should probably also handle `START` and `STOP` events, but I am a bit confused about when the extension sends them, because it doesn't when the extension is already open on page load. Got to this state so far: https://gist.github.com/lukasmoellerch/b0d0dadea168fc89cf10e9d0133e2c46

Were you able to find typescript types for `__REDUX_DEVTOOLS_EXTENSION__`?

**Comment by lostpebble** [comment]
Yep, I've just released `1.15.0` which makes use of `registerInDevtools({ UIStore })` - this has the added effect of letting us "namespace" the stores nicely in the dev tools.

I've tested it on my side and all seems to be working with my app, even with `replace`.

> I would've expected a useStoreStateOpt listener to update also if a parent changed - is that not yet implemented? (i.e. if something listens to ["a", "b", "c"] I would expect that it is called when "a" is updated)

Yes, this was one of the issues if I remember. I will need to revisit it again soon, as it does definitely have its uses. Another big issue for me was Typescript not making life easy for selecting state using an array of deep key values. It was a big headache and I decided to just put it on the back burner for a while.

> Were you able to find typescript types for __REDUX_DEVTOOLS_EXTENSION__?

I didn't - but its not a massive deal, as its just a small interface to deal with. Perhaps as we extend the functionality, and iron out those initiating state event problems, we can use the types.

**Comment by lostpebble** [comment]
You can see the first example you created, working here: https://codesandbox.io/s/pullstate-client-only-example-8b2gr?file=/src/index.tsx

**Comment by lostpebble** [comment]
Just want to say thanks so much @lukasmoellerch ! This is a great change, and you championed it. Its been ages since I used Redux Devtools, so I kind of forgot the usefulness in it - but playing around with it now, its really a great addition to the development toolkit. Will save a lot of random `console.log(state)` situations!

Test it out, and let me know if there's still some issues. As far as I can tell, it is working pretty well with the initial state and then subsequent changes.

> I also noticed that I was using you subscribe API in a a wrong way...

Its actually not too bad to use it like that, as its more "bare metal" -as its not actually subscribing, but basically listening to every change. As its running the checks inside of the state-selector for what to subscribe to. I actually left it the way you had it.

**Comment by lukasmoellerch** [comment]
@lostpebble Thank you for adding the integration so quickly! It works like a charm. A little thing I noticed is that if you don't have the devTools open when the page is loaded and open it afterwards it doesn't register correctly. It does fire a `START` event, but I am not sure what we have to do in the callback. Everything else works great.

**Comment by lostpebble** [comment]
I just released `1.15.2` which uses proper subscription behavior, and seems to be picking up on only the actual changes happening nicely.

I've noticed as well that opening two apps can be a bit weird, because maybe you named the stores the same. So you can pass a `namespace` option to `registerInDevtools()` now as well, which will prefix to your stores' names.

> A little thing I noticed is that if you don't have the devTools open when the page is loaded and open it afterwards it doesn't register correctly.

Strange, I've been trying to get this same behavior now, but I can't reproduce it. It seems like it works fine starting from closed. If you have an code sandbox where that happens, I'll check it out.

**Comment by lukasmoellerch** [comment]
> I've noticed as well that opening two apps can be a bit weird, because maybe you named the stores the same. So you can pass a namespace option to registerInDevtools() now as well, which will prefix to your stores' names.

Namespacing the stores seems like a good idea, but that won't help when you have the same app open multiple times or does it? How does redux itself handle this? It seems like redux DevTools doesn't care about what tab it is "attached" to.

> Strange, I've been trying to get this same behavior now, but I can't reproduce it. It seems like it works fine starting from closed. If you have an code sandbox where that happens, I'll check it out.

Your code sandbox is already an example where I can reproduce the error. 

https://8b2gr.csb.app/ - `No store found. Make sure to follow the instructions.`

I am using Redux DevTools v2.17.1 on Firefox - if that helps.

**Comment by lostpebble** [comment]
Ah, that must be it. I'm having no issue on Chrome with the redux tools. So likely an issue on the tooling side perhaps?

> Namespacing the stores seems like a good idea, but that won't help when you have the same app open multiple times or does it? How does redux itself handle this? It seems like redux DevTools doesn't care about what tab it is "attached" to.

Ah yea.. good point. Well, we could maybe integrate a 4 character random string on registration as well... though its not pretty in the tool UI.

Yea its a little annoying that redux devtools doesn't actually focus itself on whatever app you are currently tabbed on. Not a great UX.

**Comment by lukasmoellerch** [comment]
> Ah, that must be it. I'm having no issue on Chrome with the redux tools. So likely an issue on the tooling side perhaps?

Could be a limitation of Firefox. I just installed Redux DevTools in Chrome and everything worked like I expected.

> Ah yea.. good point. Well, we could maybe integrate a 4 character random string on registration as well... though its not pretty in the tool UI.

I don't think it's a major issue if the stores of multiple tabs with the same application have the same name (redux has the same problem and a proper solution would require changes in the devtools itself). If there are store names that are used in multiple applications we should consider copying redux and setting `document.title` as the default namespace (https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#name). I am not a big fan of the 4 character random string and as a developer would prefer to close the second tab instead of remembering the random string.

**Comment by lostpebble** [comment]
> If there are store names that are used in multiple applications we should consider copying redux and setting document.title as the default namespace

Not a bad idea. For now being able to provide a namespace directly seems like the most stable solution - but I'll add that in as the default "namespace" if you don't provide one.

> And maybe we also want to provide a default config that is merged with an optional parameter one can pass to registerInDevtools

Yea, agreed. Better to give the developer full reign of the configuration instead of trying to cover every case ourselves.

**Comment by gox-ai** [comment]
I suppose this will only work in development version of react? I am unable to get it working in production version.

**Comment by lostpebble** [comment]
I've got an app in production and just checked- it is working from my end. Did you register your stores with `registerInDevtools()` ?

Will need to add the documentation now as well.

**Comment by gox-ai** [comment]
> I've got an app in production and just checked- it is working from my end. Did you register your stores with `registerInDevtools()` ?

I  did, probably something wrong with my environment... Thank you for getting this up so quickly.
