### ISSUE TITLE
using pullstate as localState

### ISSUE THREAD

**Issue by prabirshrestha** [lostpebble/pullstate#56]
One issue I find with using `useState` is that it causes re-rendering of the entire component tree. Using local pullstate would solve this. Here is an example:

```javascript
import React, { useState } from "react";
import { Store } from "pullstate";

const createPageStore = () => {
  console.log("Page Store created");
  return new Store({
    items: [1, 2, 3, 4, 5],
    selectedId: undefined,
    itemsById: {
      1: { name: "One" },
      2: { name: "Two" },
      3: { name: "Three" },
      4: { name: "Four" },
      5: { name: "Five" }
    }
  });
};

function ListItem({ pageStore, id }) {
  const item = pageStore.useState((s) => s.itemsById[id], [id]);
  const selected = pageStore.useState((s) => s.selectedId === id, [id]);
  console.log("Render ListItem", item);

  const selectItem = () =>
    pageStore.update((s) => {
      s.selectedId = id;
    });

  return (
    <div
      onClick={selectItem}
      style={{
        color: selected ? "red" : "black",
        cursor: "pointer"
      }}
    >
      {item.name}
    </div>
  );
}

function List({ pageStore }) {
  const items = pageStore.useState((s) => s.items);
  console.log("Render list", items);

  return (
    <ul>
      {items.map((item) => (
        <ListItem key={item} pageStore={pageStore} id={item} />
      ))}
    </ul>
  );
}

export function Page() {
  const [pageStore] = useState(() => createPageStore());
  console.log("Page render");

  return (
    <div>
      <List pageStore={pageStore} />
    </div>
  );
}

export default function App() {
  return <Page />;
}
```

In this example clicking on an item will change the `selectedItem` and will only re-render 2 list items at max.

In this example: `const [pageStore] = useState(() => createPageStore());` seems like a hack.

Mobx has concept of `useLocalStore()`. Is there an equivalent for pullstate? I couldn't find one. Another option could be to add "Guide" section in docs which includes some of these examples.

(In real life `items` and `itemsById` might be a different store but this gives an example of where a page may contain few state such as `selectedItem`)

**Comment by lostpebble** [comment]
Hi,

I'll look into this more, but on my first view - it seems like you're losing most of the advantages of using Pullstate and kind of bending it into something that it isn't suited for.

If all you're looking for is a local store that works in the same way, I'd recommend adding [use-immer](https://github.com/immerjs/use-immer) into your toolbox. I use it too for cases where I only want local state and using Pullstate's more "global" style stores is not necessary.

I'm struggling to see how creating a local store here as opposed to using a regular store is going to cause less re-renders. You've already set it up quite smartly with the item `id`s and pulling in the item information inside the `<ListItem/>` item.

If you can create a reproduction in code sandbox or something, with some `console.log()` on renders, it'll be helpful to see what you mean.

Not sure if I've caught everything you're asking though, will give it another look over soon.

**Comment by prabirshrestha** [comment]
The goal is to build something like list view with command bar, search and selection.

![image](https://user-images.githubusercontent.com/287744/91663465-d0ad3a00-ea9d-11ea-888f-bd47d311a40e.png)

Few things to notice.
1. When selecting a file with different extensions or folders the command bar will change.
2. Search is local to that instance of the file explorer.
3. You have concept of selected items.
4. You can have multiple different instances of file explorer so a global one doesn't make sense here.
5. Each file/folder attributes such as hidden state, extension could be changed so each item should only subscribe to the minimal change it has. 

One issue with immer is that it doesn't have `getSubState` which is like computed though it could be easily built.

The good part about using pullstate instead is that there is now only one api to learn and you get `getSubState`.

Another option is to use context but I explicitly didn't use it since it root path might be different for different file explorer and that would need to change the context. With state it is lot easy since you could define a prop.

Sandbox link: https://codesandbox.io/s/agitated-hermann-zz298

**Comment by lostpebble** [comment]
Hmm I see.

> You can have multiple different instances of file explorer so a global one doesn't make sense here.

What about keeping a list of instance IDs as well? I think what you're trying to achieve can be done with all the benefits of global state management.

Maybe your store could look something like:

```ts
const FileManagerStore = new Store({
  currentInstanceId: 0,
  instanceIds: [0],
  instances: {
    0: {
      items: [1, 2, 3, 4, 5],
    selectedId: undefined,
    itemsById: {
      1: { name: "One" },
      2: { name: "Two" },
      3: { name: "Three" },
      4: { name: "Four" },
      5: { name: "Five" }
    }
    }
  },
  });
```

And maybe your `<Page/>` component could look like:


```ts
export function Page() {
  const instanceId = FileManagerStore.useState(s => s.currentInstanceId);
  console.log("Page render");

  return (
    <div>
      <List instanceId={instanceId} />
    </div>
  );
}
```

I obviously don't know all the details about what you're trying to achieve - but I do think that most app designs are possible with a smart store structure. An added benefit of the structure I showed you now is that your state is saved between window instance changes.

I think you are already on the right track with the way you structured your item list, it prevent re-renders because the items themselves only listen to their own state, as opposed to the outer parent `<list/>`.

As per your original issue though, you said:

> One issue I find with using useState is that it causes re-rendering of the entire component tree. Using local pullstate would solve this. 

I'm still trying to understand what you mean here. It should not render any more than than doing it locally.

**Comment by lostpebble** [comment]
> Mobx has concept of useLocalStore(). Is there an equivalent for pullstate? I couldn't find one. Another option could be to add "Guide" section in docs which includes some of these examples.

I can understand the benefits of having this anyway, so I'll look into adding it. There have been times where I would have liked having a local store with a lifetime on the component and the same Pullstate interface.

Internally it would probably pretty much look like what you're doing here:

```ts
const [pageStore] = useState(() => createPageStore());
```

Or maybe make use of `useRef` since it would never need to be updated.

Thanks for the interesting use case, btw.

**Comment by prabirshrestha** [comment]
having the lifetime of the component is the most important one since I can allow javascript to do its garbage collection without me having manual removal.

Refs are better in this case I explicitly used state just to have a proof of concept since useState already takes a callback function which gets lazily instantiated.

Also would need to support dependencies.

```js
const [pageStore] = useState(() => createPageStore(id), [id]);
```



One interesting thing for pullstate would be how would async work when a Store gets unmounted. This was another one  I wanted to ask even without local store state. I was looking for something like `store.dispose()`

**Comment by lostpebble** [comment]
> One interesting thing for pullstate would be how would async work when a Store gets unmounted. This was another one I wanted to ask even without local store state. I was looking for something like `store.dispose()`

I'm pretty much ready to release the local store's stuff now - but yea this is something I'm not entirely sure about. Wouldn't the store just automatically be removed from memory because there are no more references to it in the code? Since the React component would have unmounted.

The code pretty much boils down to this now:

```ts
function useLocalStore<S>(initialState: (() => S) | S, deps?: ReadonlyArray<any>): Store<S> {
  const storeRef = useRef<Store<S>>();

  if (storeRef.current == null) {
    storeRef.current = new Store(typeof initialState === "function" ? (initialState as any)() : initialState);
  }

  if (deps !== undefined) {
    const prevDeps = useRef<ReadonlyArray<any>>(deps);
    if (!isEqual(deps, prevDeps)) {
      storeRef.current = new Store(typeof initialState === "function" ? (initialState as any)() : initialState);
    }
  }

  return storeRef.current;
}

export { useLocalStore };
```

The only reference to the store would be here inside the `storeRef` - which should be cleaned up after the component is unmounted. Any late calls to `store.update()` would happen technically - but they would not do anything, because its using the same listener behavior as usual (its a regular store, after all).

I'm considering also adding these two convenience methods on Stores:

```ts
  Store.useLocalCopyInitial(deps?: ReadonlyArray<any>): Store<S> {
    return useLocalStore(() => this.initialState, deps);
  }

  Store.useLocalCopySnapshot(deps?: ReadonlyArray<any>): Store<S> {
    return useLocalStore(this.currentState, deps);
  }
```

The first will give you a fresh local store with state set to whatever it was initially (whatever you passed in when you created the store). The second will give you a fresh local store with state set to a snapshot of the current state of the store- I think this could come in quite handy for things like mutating state and then either applying it to the "origin" store or disregarding it.

Anyway, just thought I'd give you an update and see if you had any thoughts before I go ahead with the next version with these features.

**Comment by prabirshrestha** [comment]
Appreciate sharing the details earlier.

GC should be able to collect once the component unmount so that should be ok.

I would want to be able to also provide custom `isEqual` function for `useLocalStore` which is optional. This is primarily for dealing with legacy code base which doesn't treat complex objects in props as immutable.

```
const store = useLocalStore(() => list.split(','), [list], (a, b) => isListEqual(a, b));
```

Above one is a simple data structure but is required when dealing with complex datastrucutre such as converting my own data structure to draft js editor state which can be very expensive. One of the goals I would like to use `pullstate` is to created derived data from complex props.

I'm not sure about the use case of the other two apis `useLocalCopyInitial` and `useLocalCopySnapshot`. my goal was to have minimal api changes so one can easily migrate from react hooks to pullstate or from global pullstate to localstate. My confusion might be coming from where is `this`.

**Comment by lostpebble** [comment]
> I would want to be able to also provide custom isEqual function for useLocalStore which is optional. This is primarily for dealing with legacy code base which doesn't treat complex objects in props as immutable.

Hmm, I'm not quite sure I full grasp what you're looking for? You want this custom function to take over the dependency equality check? Internally it uses `fast-deep-equal` which has always been very efficient (even for very complex data structures- it fails fast). But yea, just would like to know what you mean here. It seems like a bit of a rare use-case and I'd like to not conflate the API too much with things from the get go. If anything, the third value would be an options object so it allows the API to extend easily instead of endless horizontal parameters. Maybe with a structure like so, to start off with:

```ts
{ depEqualityCheck: (a: Dep, b: Dep) => boolean; }
```

> I'm not sure about the use case of the other two apis useLocalCopyInitial and useLocalCopySnapshot. my goal was to have minimal api changes so one can easily migrate from react hooks to pullstate or from global pullstate to localstate. My confusion might be coming from where is this.

The `this` is nothing to worry about from an end-user's perspective. Its simply the internal workings of the store, values that have always been there - `this.currentState` is the current state, and `this.initialState` is the initial state (used mostly for SSR when creating fresh store's for each client render). I know it looks confusing because of the way I presented it (sorry!), you would call those functions directly inside your components like so:

```ts
const store = UserStore.useLocalCopySnapshot();

// pretty much the same as using the new hook like so

const storeState = UserStore.useState();
const store = useLocalStore(storeState);
```

As I said, I can see some interesting uses with it in editing scenarios where you might not want to save any changes and revert to the "original" again. But yea, mostly you would be using `useLocalStore()` in whichever custom way you like.

**Comment by prabirshrestha** [comment]
For now I'm ok not having deepEquality check. Since this can be added in the future without breaking api changes.

for my case I will mainly be using it for this case.

```js
function MyPage() {
    const store = useLocalStore(() => {
        selectedItem: null,
        searchText: ''
    });

    return <div>...<div>;
}
```

**Comment by lostpebble** [comment]
Okay cool, I've updated the library to `1.17.0` - you should be able to make use of `useLocalStore` now. Let me know if you run into any issues, or think anything else could be improved about it!
