### ISSUE TITLE
Pullstate detected an infinite loop caused by cacheBreakHook()

### ISSUE THREAD

**Issue by ultd** [lostpebble/pullstate#72]
Hello,

I am currently getting the following error: 

```
index.js:1 [1-{id(1)}] Pullstate detected an infinite loop caused by cacheBreakHook()
returning true too often (breaking cache as soon as your action is resolving - hence
causing beckoned actions to run the action again) in one of your AsyncActions - Pullstate prevented
further looping. Fix in your cacheBreakHook() is needed.
```

With the following async action: 

```ts
const getAppByID = createAsyncAction(
	async ({ id }: { id: number }) => {
		const { body, error } = await api.get('/app/' + id)
		if (error) {
			return errorResult([], '', error)
		}

		return successResult(body!)
	},
	{
		postActionHook: ({ result }) => {
			if (!result.error) {
				_upsert(result.payload)
			}
		},
		cacheBreakHook: () => true
	}
)
```

I would like the action to always be run (never cache a response). Any ideas what I may be doing wrong? 

Thanks!

**Comment by lostpebble** [comment]
Hi @ultd ,

The problem here is that every time your app encounters your async action during the render cycle (I assume you're using `useBeckon()` or `use()`) - it is going to decide if it should disregard the current cached value, or return what is cached.

Since you've put:

```ts
cacheBreakHook: () => true
```

it is going to always disregard the cached value on ever render, hence causing a loop.

I think there could be a better way to deal with this internally, which I'll look into in the future. Perhaps for the same arguments, and if it has already been resolved, we should just return the same result.

For now you could use `useDefer()` to have better control and get around this:

```ts
const myDeferredAction = MyAction.useDefer();

useEffect(() => {
  myDeferredAction.execute(args);
}, [args])
```

Now your action would only be executed on the initial render of a component, per the arguments.

I'll look into making this kind of functionality the default in the future.

**Comment by lostpebble** [comment]
I can understand that this is surprising behaviour, and actually I've run into this a couple times in my own apps.

I think I will be changing the default to work similar to `useState()` - where if the component has already been rendered, its not going to try and "reinitialize" the pulled value each time the component is rendered- even if you have a cache break hook like the one you're using ( `() => true` - never cache).

**Comment by ultd** [comment]
Thanks for the feedback! I will go ahead and use `useDefer` for now until you've made it default behavior. I definitely think others will run into similar situations so I agree with changing the default behavior. I look forward to the release.

**Comment by lostpebble** [comment]
I did a bit of internal re-writing of the caching stuff in Async Actions. This should be fixed by this release: https://github.com/lostpebble/pullstate/releases/tag/1.21.0

Also, you can now define cache breaking inline, where you actually make use of the action:

```ts
const getImagesAction = GetImages.use({ tag: "green" }, { cacheBreak: true });
```

This will cause the cache to always break when this component is mounted for the first time (good for things like a user account screen, where you always want to load the latest data, so they can update on top of that).
