### ISSUE TITLE
Getting '_asyncCache' of null error when building pre-render of site

### ISSUE THREAD

**Issue by robertpage** [lostpebble/pullstate#88]
So I've been really loving Pullstate. I'm using it in a Preact CLI project, which uses react-compat. Everything has been working flawlessly in dev. When I attempt to do a build the CLI tries to pre-render pages. Everything is working except that I get a type error around  '_asyncCache' from Pullstate dist file.

I wouldn't be posting but it looks more like a typescript error that could possible be accounted for? I'm not sure though. This may also just be a Preact pre-render incompatibility that is outside of the scope of Pullstate, which I would completely understand. Either way, I'm a bit stumped by the issue and was hoping for either a fix or "move along".

This is the error output:
` Build  [=================== ] 95% (18.4s) emittingUnable to read file: /Users/robert/viewer/frontend/app/src/node_modules/pullstate/dist/index.es.js

TypeError: Cannot read property '_asyncCache' of null
method: null`

Happy to provide any other info. Thanks in advance!

**Comment by lostpebble** [comment]
Hmm, so what I assume is happening is that `<PullstateProvider>` is missing- because building is happening in the "server" context, in Node.js, Pullstate will look for things which are usually available during Server-side rendering- which relies on a certain context being passed down (because each page rendered on the server needs to contain its state separately as opposed to globally like on the client).

If you are making use of Async Actions and don't need server-side rendering at all- you could pass the option `ssr: false` into your actions- this will make them only execute on the client side. The build process should ignore them then as well... (Though I could be wrong, it may still look for the context and throw an error).

If on the other hand, its important that the Async Actions are resolved during the building process, then you would need to provide a [PullstateProvider](https://lostpebble.github.io/pullstate/docs/quick-example-server-rendered#server-rendering-our-app).

The `<PullstateProvider>` will supply the context object which contains `_asyncCache`- which will then get rid of the error. So you basically just need to wrap your app with that.

The only other thing would be to create a Pullstate "core":

```tsx
import { UIStore } from "./stores/UIStore";
import { createPullstateCore } from "pullstate";

export const PullstateCore = createPullstateCore({
  UIStore
});
```

This is what you would pass into the provider like so:

```tsx
const instance = PullstateCore.instantiate({ ssr: true });

// later
<PullstateProvider instance={instance}>
   <App />
</PullstateProvider>
```

Hope that helps, let me know if you still run into any issues- or if your situation is actually a little different to what I interpreted.

**Comment by robertpage** [comment]
Thank you! Everything you're saying here makes sense. This is definitely on me. I think if I had gone through the last of the documentation better I probably would have eventually figured out a solution.

I had been setting the "ssr: false" option on all my useBeckon hooks when I was trying to figure it out originally. That didn't really change the outcome for me. Using PullstateProvider really was the answer. Everything works perfectly now. I get a nicely pre-rendered site from the Preact CLI. Thanks again for the help and such an awesome library!

**Comment by lostpebble** [comment]
Great! Glad to hear its resolved.

I think I need to look into making this kind of thing function without the `<PullstateProvider>` for folks like yourself who are not actually making use of any SSR functionality. It is quite surprising behaviour, so I don't blame you at all for running into it and being a lil confused.

Anyway, no worries, and thanks for the kind words- happy hacking on whatever you're up to! :)
